### ISSUE TITLE
cns_max_freq_*.fasta contains reference sequence at low/not covered positions

### ISSUE THREAD

**Issue by sschmutz** [medvir/MinVar#28]
MinVar output (fasta files):
Compared to the `cns_ambiguous_*.fasta` where the low (threshold?) covered bases are `N`, in the `cns_max_freq_*.fasta` those positions seem to be replaced by the closest reference sequence out of `subtype_references.fasta`.
Not sure if it's a bug or a feature, but it's important to know and keep in mind if one's working with those data.

**Comment by sschmutz** [comment]
On that topic, the two output files `cns_ambiguous.fasta` and `cns_max_freq.fasta` are described in the code but not in the documentation (https://minvar.readthedocs.io/en/latest/#output-files).

**Comment by ozagordi** [comment]
After discussion, we decided to keep both fasta files. The differences between them was only reported in the docstrings of `annotate.py`, now reported in the documentation on readthedocs.

**Comment by sschmutz** [comment]
The same is true for the file `merged_mutations_nt.csv`. At positions with low/no coverage (can be because the gap is real or the actual sequence is not close enough to the reference sequence) freq is 1 and mut is the nucleotide from the closest reference at that position.
That has to be taken into account if one would use this file for a different kind analysis. An additional column with depth would be nice.
