### ISSUE TITLE
output file containing ambiguous score

### ISSUE THREAD

**Issue by mihuber** [medvir/MinVar#32]
It would be good to have an output file 'ambiguous.txt' that contains the ambiguous score (plus maybe the absolute number of ambiguous bases and the range). It would then be possible to access this file by pybis without having to open the pdf or md file.

**Comment by ozagordi** [comment]
Or, pybis might grep the md file for the value and write it into a txt file that is attached, or into a field of the RESISTANCE_TEST object. In this case one would need to change the attributes, though. You need to think it through. My point was that MinVar might not need another output file, but it's up to you.

**Comment by mihuber** [comment]
Creating a new field would be an option, although all the other results are attachments as well and are not written into fields (e.g. subtype prediction). Anyway, we will have to learn how the access openBIS with pybis because downloading and opening 50 pdf reports to get the ambiguity score of 50 patients is not a option in the long run.

**Comment by MaryamZaheri** [comment]
Another solution would be to download and grep report markdown files on openBIS from a bash script (e.g grep [REPORT_NAME].md -e "Score:"| grep -Eo '[0-9]+([.][0-9]+)?').

**Comment by MaryamZaheri** [comment]
This is done by writing a script to downloading report.md files and extracting ambiguity score.
