### ISSUE TITLE
provide Dockerfile and ci/cd-built publicly accessible container image somewhere

### ISSUE THREAD

**Issue by Masterxilo** [medvir/MinVar#42]
I want to use this software, but I am not interested in figuring out how to set up any of its dependencies in the right versions.

Please provide a docker image of this software somewhere.

We have an automation pipeline set up here that can run any container image on our NGS data. 

A primary motivation for this setup was that our researches should not spend time figuring out how to get software to work.

We think all researchers would benefit from trying out different tools with less installation hassles.

**Comment by ozagordi** [comment]
Hi Paul!

That's why it was published as a [bioconda](http://bioconda.github.io/recipes/minvar/README.html) package. Did you already try [this container](https://quay.io/repository/biocontainers/minvar)?
