### ISSUE TITLE
Please Parametrize start_stop_coverage > threshold=20

### ISSUE THREAD

**Issue by Masterxilo** [medvir/MinVar#43]
Hi

because of quality issues with some of our samples we would like to try to vary this parameter. But it is hardcoded right now making it difficult to change it.

Please expose it as an environment variable or commandline parameter, whatever is easier.

**Comment by Masterxilo** [comment]
@MaryamZaheri : this is for Lisa

**Comment by MaryamZaheri** [comment]
Please check the research branch, parameter `-c , --cov_th` .

**Comment by Masterxilo** [comment]
seems to work, thank you!
