### ISSUE TITLE
Please Parametrize make_consensus > sampled_reads=10000

### ISSUE THREAD

**Issue by Masterxilo** [medvir/MinVar#44]
Hi

because of quality issues with some of our samples we would like to try to vary this parameter. But it is hardcoded right now making it difficult to change it.

I see that 10000 is set as a default value for the parameter but also explicitly specified on each invocation.

Please expose it as an environment variable or commandline parameter, whatever is easier.

**Comment by Masterxilo** [comment]
@MaryamZaheri : this is for Lisa

**Comment by Masterxilo** [comment]
Also, for this sampling we would like to freeze the random seed for reproducibility!

**Comment by MaryamZaheri** [comment]
Subsampling is used in different parts.  The seed given in the beginning is used in all subsamplings. However for consensus reconstruction the subsampling is done in a for loop. In order to avoid subsampling of the same reads, the iteration number is added to the provided random seed.

**Comment by MaryamZaheri** [comment]
Please check the research branch. You can set `-s, --subsample_randseed` and `-n, --subsample_consensus` parameters.

**Comment by Masterxilo** [comment]
seems to work, thank you!
