### ISSUE TITLE
Please allow freezing/specifying the random seed of the subsampling of the 200k reads to enable reproducibility!

### ISSUE THREAD

**Issue by Masterxilo** [medvir/MinVar#45]
How is the randomness seeded?

**Comment by MaryamZaheri** [comment]
Please check the research branch. You can set `-s (--subsample_randseed)` parameter. 
It is used in [seqtk sample](https://github.com/lh3/seqtk) command.

**Comment by Masterxilo** [comment]
seems to work, thank you!
